# Generated by Django 5.0.3 on 2024-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='fullName',
            field=models.CharField(default='fullname', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
