# Generated by Django 5.0.3 on 2024-03-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_studentsinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
